augment: true
auto_augment: randaugment
batch_size: 4
box: 8.0
close_mosaic: 20
cls: 0.5
conf: 0.25
copy_paste: 0.1
cos_lr: true
crop_fraction: 1.0
degrees: 5.0
device: auto
dfl: 1.5
dropout: 0.2
ema: true
ema_decay: 0.9999
epochs: 100
erasing: 0.2
fliplr: 0.5
flipud: 0.0
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
imgsz: 1024
iou: 0.5
label_smoothing: 0.05
lr0: 0.001
lrf: 0.01
max_det: 300
mixup: 0.1
model: yolov8x.pt
momentum: 0.95
mosaic: 0.5
multiscale: true
names:
- FireExtinguisher
- ToolBox
- OxygenTank
nbs: 64
nc: 3
optimizer: AdamW
path: ./
patience: 25
perspective: 0.0001
plots: true
save_period: 10
scale: 0.8
scale_range:
- 0.9
- 1.1
shear: 1.0
test: data/test/images
train: data/train/images
translate: 0.1
tta: true
val: true
verbose: true
warmup_bias_lr: 0.1
warmup_epochs: 5.0
warmup_momentum: 0.8
weight_decay: 0.001
